---
hero_image: images/codecraft.png
duration: 2
listed: false
copyedit: false
title: CodeCraft
description: Design and code improvements to a 2D version of Minecraft.
version: 3.1.0
last_tested: 2018-11-22
steps:
- title: Step 1
- title: Step 2
- title: Step 3
  completion:
  - engaged
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
- title: Step 9
- title: Step 10
  completion:
  - internal
  - external
